# Read the Docs configuration file for Sphinx builds
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
#
# Project: SCORE Communication
# Recommended URL: https://score-communication.readthedocs.io/
# (Configure project slug in Read the Docs dashboard: Admin → Advanced Settings)
#
# This configuration installs Bazel and runs the full build pipeline on Read the Docs.
# Generated artifacts (Doxygen XML, API RST files, README) are created during the build.

# Required
version: 2

# Version control settings (optional - RTD will build all active versions by default)
# To control which branches/tags are built, configure in RTD dashboard: Admin → Versions
# URLs will be: /en/latest/, /en/stable/, /en/v1.0.0/, etc.

# Set the OS, Python version and other Bazel dependencies for the build environment
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    - curl
    - gnupg
  jobs:
    pre_install:
      # Install Bazelisk (Bazel version manager) to local bin directory
      - mkdir -p $HOME/.local/bin
      - curl -Lo $HOME/.local/bin/bazel https://github.com/bazelbuild/bazelisk/releases/download/v1.19.0/bazelisk-linux-amd64
      - chmod +x $HOME/.local/bin/bazel
      - $HOME/.local/bin/bazel --version
    pre_build:
      # Build complete documentation with Bazel (includes Doxygen, API RST generation, and Sphinx HTML build)
      - $HOME/.local/bin/bazel build //score/mw/com/doc/sphinx:docs
      # Copy built HTML to _readthedocs/html/ where Read the Docs expects it
      - mkdir -p _readthedocs/html
      - cp -r bazel-bin/score/mw/com/doc/sphinx/docs/* _readthedocs/html/

# Sphinx configuration is required by Read the Docs, but the actual build is done by Bazel
# Read the Docs will find the pre-built HTML in _readthedocs/html/ and use that instead
sphinx:
  configuration: score/mw/com/doc/sphinx/conf.py
  fail_on_warning: false

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - pdf
  - epub

# Python dependencies required to build your docs
python:
  install:
    - requirements: requirements_lock.txt
