# Read the Docs configuration file for Sphinx builds
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
#
# Project: SCORE Communication
# Recommended URL: https://score-communication.readthedocs.io/
# (Configure project slug in Read the Docs dashboard: Admin → Advanced Settings)
#
# This configuration installs Bazel and runs the full build pipeline on Read the Docs.
# Generated artifacts (Doxygen XML, API RST files, README) are created during the build.

# Required
version: 2

# Version control settings (optional - RTD will build all active versions by default)
# To control which branches/tags are built, configure in RTD dashboard: Admin → Versions
# URLs will be: /en/latest/, /en/stable/, /en/v1.0.0/, etc.

# Set the OS, Python version and other Bazel dependencies for the build environment
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    - curl
    - gnupg
  jobs:
    pre_install:
      # Install Bazelisk (Bazel version manager) to local bin directory
      - mkdir -p $HOME/.local/bin
      - curl -Lo $HOME/.local/bin/bazel https://github.com/bazelbuild/bazelisk/releases/download/v1.19.0/bazelisk-linux-amd64
      - chmod +x $HOME/.local/bin/bazel
      - $HOME/.local/bin/bazel --version
    pre_build:
      # Run Bazel to generate documentation artifacts (Doxygen XML and API RST files)
      - $HOME/.local/bin/bazel build //score/mw/com/doc/sphinx:generate_api_rst
      # Copy README.md to where Sphinx expects it
      - cp -f score/mw/com/README.md score/mw/com/doc/sphinx/README.md
      # Copy generated RST files to where Sphinx expects them
      - mkdir -p score/mw/com/doc/sphinx/generated
      - cp -f bazel-bin/score/mw/com/doc/sphinx/generated/*.rst score/mw/com/doc/sphinx/generated/
      # Copy Doxygen XML to the location where Breathe expects it
      - mkdir -p score/mw/com/design/doxygen_build/xml
      - cp -rf bazel-bin/score/mw/com/design/doxygen_build/xml/* score/mw/com/design/doxygen_build/xml/

# Sphinx builds the documentation using the artifacts generated by Bazel
sphinx:
  configuration: score/mw/com/doc/sphinx/conf.py
  fail_on_warning: false

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - pdf
  - epub

# Python dependencies required to build your docs
python:
  install:
    - requirements: requirements_lock.txt
