# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")
load("@score_tooling//bazel/rules/rules_score:rules_score.bzl", "component", "unit")
load("//quality/unit_testing:unit_testing.bzl", "cc_unit_test")
load("//score/mw:common_features.bzl", "COMPILER_WARNING_FEATURES")

component(
    name = "lola_component",
    components = [
        ":lola_sd",
        ":lola_skeleton",
        ":lola_proxy",
    ],
    requirements = [
    ],
    target_compatible_with = ["@platforms//os:linux"],
    tests = [],
    visibility = ["//score/mw/com/impl/bindings:__pkg__"],
)

unit(
    name = "lola_sd",
    scope = [],
    tests = [],
    unit_design = [],
    implementation = [],
)

unit(
    name = "lola_skeleton",
    scope = [],
    tests = [],
    unit_design = [],
    implementation = [],
)

unit(
    name = "lola_proxy",
    scope = [],
    tests = [],
    unit_design = [],
    implementation = [],
)

cc_library(
    name = "lola",
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = [
        "//score/mw/com/impl/bindings/lola/test:__pkg__",
        "//score/mw/com/impl/plumbing:__pkg__",
    ],
    deps = [
        ":event",
        ":proxy",
        ":runtime",
        ":skeleton",
        "//score/mw/com/impl/configuration",
        "@score_baselibs//score/concurrency",
        "@score_baselibs//score/language/futurecpp",
        "@score_baselibs//score/mw/log",
    ],
)

cc_library(
    name = "path_builder",
    srcs = ["path_builder.cpp"],
    hdrs = ["path_builder.h"],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = [
        "//score/mw/com/impl:__subpackages__",
    ],
    deps = ["//score/mw/com/impl/configuration:lola_service_instance_id"],
)

cc_library(
    name = "shm_path_builder",
    srcs = ["shm_path_builder.cpp"],
    hdrs = ["shm_path_builder.h"],
    features = COMPILER_WARNING_FEATURES,
    implementation_deps = [":path_builder"],
    tags = ["FFI"],
    visibility = ["//score/mw/com/impl/plumbing:__pkg__"],
    deps = [
        ":i_shm_path_builder",
        "//score/mw/com/impl/configuration",
    ],
)

cc_library(
    name = "partial_restart_path_builder",
    srcs = ["partial_restart_path_builder.cpp"],
    hdrs = ["partial_restart_path_builder.h"],
    features = COMPILER_WARNING_FEATURES,
    implementation_deps = [":path_builder"],
    tags = ["FFI"],
    visibility = ["//score/mw/com/impl/plumbing:__pkg__"],
    deps = [":i_partial_restart_path_builder"],
)

cc_library(
    name = "i_runtime",
    srcs = ["i_runtime.cpp"],
    hdrs = ["i_runtime.h"],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = ["//score/mw/com/impl/plumbing:__pkg__"],
    deps = [
        ":rollback_synchronization",
        "//score/mw/com/impl:runtime_interfaces",
        "//score/mw/com/impl/bindings/lola/messaging",
        "//score/mw/com/impl/configuration",
    ],
)

cc_library(
    name = "i_shm_path_builder",
    srcs = ["i_shm_path_builder.cpp"],
    hdrs = ["i_shm_path_builder.h"],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = [
        "//score/mw/com/impl:__subpackages__",
    ],
    deps = [
        ":proxy_instance_identifier",
        "//score/mw/com/impl/configuration",
        "@score_baselibs//score/language/futurecpp",
    ],
)

cc_library(
    name = "i_partial_restart_path_builder",
    srcs = ["i_partial_restart_path_builder.cpp"],
    hdrs = ["i_partial_restart_path_builder.h"],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = [
        "//score/mw/com/impl:__subpackages__",
    ],
    deps = [
        "//score/mw/com/impl/configuration",
        "@score_baselibs//score/language/futurecpp",
    ],
)

cc_library(
    name = "runtime",
    srcs = ["runtime.cpp"],
    hdrs = ["runtime.h"],
    features = COMPILER_WARNING_FEATURES,
    implementation_deps = [
        "//score/memory/shared",
        "@score_baselibs//score/mw/log",
    ],
    tags = ["FFI"],
    visibility = ["//score/mw/com/impl/plumbing:__pkg__"],
    deps = [
        ":i_runtime",
        "//score/mw/com/impl/bindings/lola/messaging",
        "//score/mw/com/impl/bindings/lola/service_discovery/client:service_discovery_client",
        "//score/mw/com/impl/bindings/lola/tracing:tracing_runtime",
        "@score_baselibs//score/concurrency:executor",
        "@score_baselibs//score/concurrency:long_running_threads_container",
        "@score_baselibs//score/language/futurecpp",
    ],
)

cc_library(
    name = "rollback_synchronization",
    srcs = ["rollback_synchronization.cpp"],
    hdrs = ["rollback_synchronization.h"],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = ["//score/mw/com/impl:__subpackages__"],
    deps = [
        ":skeleton_instance_identifier",
        "@score_baselibs//score/language/futurecpp",
    ],
)

cc_library(
    name = "runtime_mock",
    testonly = True,
    srcs = ["runtime_mock.cpp"],
    hdrs = ["runtime_mock.h"],
    features = COMPILER_WARNING_FEATURES,
    visibility = ["//score/mw/com/impl:__subpackages__"],
    deps = [
        ":i_runtime",
        "@googletest//:gtest",
    ],
)

cc_library(
    name = "shm_path_builder_mock",
    testonly = True,
    srcs = ["shm_path_builder_mock.cpp"],
    hdrs = ["shm_path_builder_mock.h"],
    features = COMPILER_WARNING_FEATURES,
    visibility = ["//score/mw/com/impl:__subpackages__"],
    deps = [
        ":i_shm_path_builder",
        "@googletest//:gtest",
    ],
)

cc_library(
    name = "partial_restart_path_builder_mock",
    testonly = True,
    srcs = ["partial_restart_path_builder_mock.cpp"],
    hdrs = ["partial_restart_path_builder_mock.h"],
    features = COMPILER_WARNING_FEATURES,
    visibility = ["//score/mw/com/impl:__subpackages__"],
    deps = [
        ":i_partial_restart_path_builder",
        "@googletest//:gtest",
    ],
)

cc_library(
    name = "event_meta_info",
    srcs = ["event_meta_info.cpp"],
    hdrs = ["event_meta_info.h"],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = [
        "//score/mw/com/impl:__subpackages__",
    ],
    deps = [
        "//score/memory/shared",
        "@score_baselibs//score/memory:data_type_size_info",
    ],
)

cc_library(
    name = "linear_search_map",
    srcs = ["linear_search_map.cpp"],
    hdrs = [
        "linear_search_map.h",
    ],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = [
        "//score/mw/com/impl/bindings/lola:__pkg__",
        "//score/mw/com/impl/bindings/lola/test_doubles:__pkg__",
    ],
    deps = [
        "//score/memory/shared",
        "@score_baselibs//score/containers:non_relocatable_vector",
    ],
)

cc_library(
    name = "service_data_storage",
    srcs = ["service_data_storage.cpp"],
    hdrs = [
        "service_data_storage.h",
    ],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = [
        "//score/mw/com/impl/bindings/lola:__pkg__",
        "//score/mw/com/impl/bindings/lola/test:__pkg__",
        "//score/mw/com/impl/bindings/lola/test_doubles:__pkg__",
    ],
    deps = [
        ":element_fq_id",
        ":event_data_storage",
        ":event_meta_info",
        ":i_runtime",
        ":linear_search_map",
        "//score/memory/shared",
        "//score/memory/shared:pointer_arithmetic_util",
        "//score/mw/com/impl:runtime",
        "@score_baselibs//score/containers:non_relocatable_vector",
        "@score_baselibs//score/language/futurecpp",
        "@score_baselibs//score/memory:data_type_size_info",
        "@score_baselibs//score/os:unistd",
    ],
)

cc_library(
    name = "service_data_control",
    srcs = ["service_data_control.cpp"],
    hdrs = ["service_data_control.h"],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = [
        "//score/mw/com/impl/bindings/lola/test:__pkg__",
        "//score/mw/com/impl/bindings/lola/test_doubles:__pkg__",
    ],
    deps = [
        ":application_id_pid_mapping",
        ":application_id_pid_mapping_entry",
        ":element_fq_id",
        ":event_control",
        ":event_data_control",
        ":linear_search_map",
        ":transaction_log",
        ":transaction_log_set",
        "//score/memory/shared",
        "//score/memory/shared:pointer_arithmetic_util",
        "@score_baselibs//score/language/futurecpp",
        "@score_baselibs//score/memory:data_type_size_info",
    ],
)

cc_library(
    name = "generic_skeleton_event",
    srcs = [
        "generic_skeleton_event.cpp",
    ],
    hdrs = [
        "generic_skeleton_event.h",
    ],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = [
        "//score/mw/com/impl:__subpackages__",
    ],
    deps = [
        ":event",
        ":skeleton",
        ":type_erased_sample_ptrs_guard",
        "//score/mw/com/impl:error",
        "//score/mw/com/impl:generic_skeleton_event_binding",
        "//score/mw/com/impl/tracing:skeleton_event_tracing",
    ],
)

cc_library(
    name = "skeleton",
    srcs = [
        "skeleton.cpp",
        "skeleton_event.cpp",
        "skeleton_event_common.cpp",
        "skeleton_event_properties.cpp",
        "skeleton_memory_manager.cpp",
        "skeleton_method.cpp",
    ],
    hdrs = [
        "skeleton.h",
        "skeleton_event.h",
        "skeleton_event_common.h",
        "skeleton_event_properties.h",
        "skeleton_memory_manager.h",
        "skeleton_method.h",
    ],
    features = COMPILER_WARNING_FEATURES,
    implementation_deps = [
        "//score/mw/com/impl/bindings/lola/tracing:tracing_runtime",
    ],
    tags = ["FFI"],
    visibility = [
        "//score/mw/com/impl/bindings/lola/test:__pkg__",
        "//score/mw/com/impl/bindings/lola/test_doubles:__pkg__",
    ],
    deps = [
        ":event",
        ":i_partial_restart_path_builder",
        ":i_shm_path_builder",
        ":partial_restart_path_builder",
        ":proxy_instance_identifier",
        ":service_data_control",
        ":service_data_storage",
        ":shm_path_builder",
        ":skeleton_instance_identifier",
        ":type_erased_sample_ptrs_guard",
        "//score/memory/shared",
        "//score/memory/shared:i_shared_memory_resource",
        "//score/memory/shared:lock_file",
        "//score/memory/shared:new_delete_delegate_resource",
        "//score/memory/shared/flock:exclusive_flock_mutex",
        "//score/memory/shared/flock:flock_mutex_and_lock",
        "//score/mw/com/impl:error",
        "//score/mw/com/impl:generic_skeleton_event_binding",
        "//score/mw/com/impl:instance_identifier",
        "//score/mw/com/impl:runtime",
        "//score/mw/com/impl:skeleton_binding",
        "//score/mw/com/impl:skeleton_event_binding",
        "//score/mw/com/impl/bindings/lola/methods:method_data",
        "//score/mw/com/impl/bindings/lola/methods:method_resource_map",
        "//score/mw/com/impl/bindings/lola/methods:type_erased_call_queue",
        "//score/mw/com/impl/configuration",
        "//score/mw/com/impl/e2e:e2e_profile_stub",
        "//score/mw/com/impl/methods:skeleton_method_binding",
        "//score/mw/com/impl/plumbing:sample_allocatee_ptr",
        "//score/mw/com/impl/plumbing:sample_ptr",
        "//score/mw/com/impl/tracing:skeleton_event_tracing",
        "//score/mw/com/impl/util:arithmetic_utils",
        "@score_baselibs//score/filesystem",
        "@score_baselibs//score/language/futurecpp",
        "@score_baselibs//score/language/safecpp/safe_math",
        "@score_baselibs//score/language/safecpp/scoped_function:scope",
        "@score_baselibs//score/memory:data_type_size_info",
        "@score_baselibs//score/result",
    ],
)

cc_library(
    name = "proxy",
    srcs = [
        "generic_proxy_event.cpp",
        "proxy.cpp",
        "proxy_event.cpp",
        "proxy_event_common.cpp",
        "proxy_method.cpp",
    ],
    hdrs = [
        "generic_proxy_event.h",
        "proxy.h",
        "proxy_event.h",
        "proxy_event_common.h",
        "proxy_method.h",
    ],
    features = COMPILER_WARNING_FEATURES,
    implementation_deps = [
        ":service_data_control",
        ":shm_path_builder",
        ":transaction_log_rollback_executor",
        "//score/mw/com/impl:runtime",
        "//score/mw/com/impl/bindings/lola:partial_restart_path_builder",
        "@score_baselibs//score/language/safecpp/safe_atomics:try_atomic_add",
        "@score_baselibs//score/os:errno_logging",
    ],
    tags = ["FFI"],
    visibility = ["//score/mw/com/impl/bindings/lola/test:__pkg__"],
    deps = [
        ":event",
        ":event_control",
        ":event_subscription_control",
        ":proxy_instance_identifier",
        ":service_data_storage",
        ":slot_collector",
        ":subscription_state_machine",
        ":transaction_log_id",
        "//score/memory/shared",
        "//score/memory/shared:lock_file",
        "//score/memory/shared:pointer_arithmetic_util",
        "//score/memory/shared/flock:flock_mutex_and_lock",
        "//score/memory/shared/flock:shared_flock_mutex",
        "//score/mw/com/impl:find_service_handle",
        "//score/mw/com/impl:generic_proxy_event_binding",
        "//score/mw/com/impl:instance_identifier",
        "//score/mw/com/impl:instance_specifier",
        "//score/mw/com/impl:proxy_binding",
        "//score/mw/com/impl:proxy_event_binding",
        "//score/mw/com/impl:runtime_interfaces",
        "//score/mw/com/impl:scoped_event_receive_handler",
        "//score/mw/com/impl/bindings/lola/methods:method_data",
        "//score/mw/com/impl/bindings/lola/methods:offered_state_machine",
        "//score/mw/com/impl/bindings/lola/methods:type_erased_call_queue",
        "//score/mw/com/impl/configuration",
        "//score/mw/com/impl/e2e:e2e_profile_stub",
        "//score/mw/com/impl/methods:proxy_method_binding",
        "//score/mw/com/impl/plumbing:sample_ptr",
        "//score/mw/com/impl/tracing:i_tracing_runtime",
        "//score/mw/com/impl/util:type_erased_storage",
        "@score_baselibs//score/filesystem",
        "@score_baselibs//score/language/safecpp/safe_math",
        "@score_baselibs//score/mw/log",
        "@score_baselibs//score/os:fcntl",
        "@score_baselibs//score/os:glob",
        "@score_baselibs//score/os:unistd",
        "@score_baselibs//score/result",
    ],
)

cc_library(
    name = "element_fq_id",
    srcs = ["element_fq_id.cpp"],
    hdrs = ["element_fq_id.h"],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = [
        "//score/mw/com/impl/bindings/lola:__subpackages__",
        "//score/mw/com/impl/plumbing:__subpackages__",
    ],
    deps = [
        "//score/mw/com/impl:service_element_type",
        "//score/mw/com/impl/configuration",
        "@score_baselibs//score/mw/log",
    ],
)

cc_library(
    name = "sample_ptr",
    srcs = ["sample_ptr.cpp"],
    hdrs = ["sample_ptr.h"],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = [
        "//score/mw/com/impl:__subpackages__",
    ],
    deps = [
        ":consumer_event_data_control_local_view",
        ":slot_decrementer",
    ],
)

cc_library(
    name = "slot_decrementer",
    srcs = ["slot_decrementer.cpp"],
    hdrs = ["slot_decrementer.h"],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = [
        "//score/mw/com/impl:__subpackages__",
    ],
    deps = [
        ":consumer_event_data_control_local_view",
        ":control_slot_types",
    ],
)

cc_library(
    name = "subscription_state_machine",
    srcs = [
        "subscription_helpers.cpp",
        "subscription_not_subscribed_states.cpp",
        "subscription_state_base.cpp",
        "subscription_state_machine.cpp",
        "subscription_state_machine_states.cpp",
        "subscription_subscribed_states.cpp",
        "subscription_subscription_pending_states.cpp",
    ],
    hdrs = [
        "subscription_helpers.h",
        "subscription_not_subscribed_states.h",
        "subscription_state_base.h",
        "subscription_state_machine.h",
        "subscription_state_machine_states.h",
        "subscription_subscribed_states.h",
        "subscription_subscription_pending_states.h",
    ],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    deps = [
        ":consumer_event_data_control_local_view",
        ":event_subscription_control",
        ":i_runtime",
        ":slot_collector",
        ":transaction_log_id",
        ":transaction_log_index",
        ":transaction_log_set",
        "//score/mw/com/impl:runtime",
        "//score/mw/com/impl:scoped_event_receive_handler",
        "//score/mw/com/impl:subscription_state",
        "//score/mw/com/impl:subscription_state_change_handler",
        "//score/mw/com/impl/bindings/lola/messaging:i_message_passing_service",
    ],
)

cc_library(
    name = "slot_collector",
    srcs = ["slot_collector.cpp"],
    hdrs = ["slot_collector.h"],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    deps = [
        ":consumer_event_data_control_local_view",
        ":event_slot_status",
    ],
)

cc_library(
    name = "application_id_pid_mapping",
    srcs = ["application_id_pid_mapping.cpp"],
    hdrs = ["application_id_pid_mapping.h"],
    features = COMPILER_WARNING_FEATURES,
    implementation_deps = ["@score_baselibs//score/mw/log"],
    tags = ["FFI"],
    visibility = ["//score/mw/com/impl/bindings/lola:__subpackages__"],
    deps = [
        ":application_id_pid_mapping_entry",
        ":register_pid_fake",
        "//score/memory/shared:types",
        "@score_baselibs//score/concurrency:atomic_indirector",
        "@score_baselibs//score/containers:dynamic_array",
    ],
)

cc_library(
    name = "application_id_pid_mapping_entry",
    srcs = ["application_id_pid_mapping_entry.cpp"],
    hdrs = ["application_id_pid_mapping_entry.h"],
    features = COMPILER_WARNING_FEATURES,
    implementation_deps = ["@score_baselibs//score/mw/log"],
    tags = ["FFI"],
    visibility = ["//score/mw/com/impl/bindings/lola:__subpackages__"],
    deps = [],
)

cc_library(
    name = "register_pid_fake",
    srcs = ["register_pid_fake.cpp"],
    hdrs = ["register_pid_fake.h"],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = ["//score/mw/com/impl:__subpackages__"],
    deps = [
        ":application_id_pid_mapping_entry",
        "@score_baselibs//score/containers:dynamic_array",
    ],
)

cc_library(
    name = "event_data_control",
    srcs = ["event_data_control.cpp"],
    hdrs = ["event_data_control.h"],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = ["//score/mw/com/impl/bindings/lola:__subpackages__"],
    deps = [
        ":control_slot_types",
        "//score/memory/shared:types",
        "@score_baselibs//score/containers:dynamic_array",
    ],
)

cc_library(
    name = "provider_event_data_control_local_view",
    srcs = ["provider_event_data_control_local_view.cpp"],
    hdrs = ["provider_event_data_control_local_view.h"],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = ["//score/mw/com/impl/bindings/lola:__subpackages__"],
    deps = [
        ":control_slot_types",
        ":event_data_control",
        ":event_slot_status",
        "@score_baselibs//score/concurrency:atomic_indirector",
    ],
)

cc_library(
    name = "consumer_event_data_control_local_view",
    srcs = ["consumer_event_data_control_local_view.cpp"],
    hdrs = ["consumer_event_data_control_local_view.h"],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = ["//score/mw/com/impl/bindings/lola:__subpackages__"],
    deps = [
        ":control_slot_types",
        ":event_data_control",
        ":event_slot_status",
        ":transaction_log_local_view",
        "@score_baselibs//score/concurrency:atomic_indirector",
    ],
)

cc_library(
    name = "control_slot_types",
    srcs = ["control_slot_types.cpp"],
    hdrs = ["control_slot_types.h"],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = [
        "//score/mw/com/impl:__subpackages__",
    ],
    deps = [
        ":event_slot_status",
    ],
)

cc_library(
    name = "event_control",
    srcs = ["event_control.cpp"],
    hdrs = ["event_control.h"],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = ["//score/mw/com/impl/bindings/lola:__subpackages__"],
    deps = [
        ":control_slot_types",
        ":event_data_control",
        ":event_subscription_control",
        ":transaction_log_set",
    ],
)

cc_library(
    name = "event_subscription_control",
    srcs = ["event_subscription_control.cpp"],
    hdrs = ["event_subscription_control.h"],
    features = COMPILER_WARNING_FEATURES,
    implementation_deps = [
        "@score_baselibs//score/language/safecpp/safe_math",
        "@score_baselibs//score/mw/log",
    ],
    tags = ["FFI"],
    visibility = ["//score/mw/com/impl/bindings/lola:__subpackages__"],
    deps = [
        "//score/mw/com/impl/configuration",
        "@score_baselibs//score/concurrency:atomic_indirector",
    ],
)

cc_library(
    name = "event_slot_status",
    srcs = ["event_slot_status.cpp"],
    hdrs = ["event_slot_status.h"],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = [
        "//score/mw/com/impl:__subpackages__",
    ],
)

cc_library(
    name = "event_data_control_composite",
    srcs = ["event_data_control_composite.cpp"],
    hdrs = ["event_data_control_composite.h"],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = [
        "//score/mw/com/impl:__subpackages__",
    ],
    deps = [
        ":consumer_event_data_control_local_view",
        ":control_slot_types",
        ":event_data_control",
        ":event_slot_status",
        ":provider_event_data_control_local_view",
        "@score_baselibs//score/concurrency:atomic_indirector",
    ],
)

cc_library(
    name = "event_data_storage",
    srcs = ["event_data_storage.cpp"],
    hdrs = ["event_data_storage.h"],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = [
        "//score/mw/com/impl:__subpackages__",
    ],
    deps = [
        "//score/memory/shared:types",
        "@score_baselibs//score/containers:dynamic_array",
    ],
)

cc_library(
    name = "sample_allocatee_ptr",
    srcs = ["sample_allocatee_ptr.cpp"],
    hdrs = ["sample_allocatee_ptr.h"],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = [
        "//score/mw/com/impl:__subpackages__",
    ],
    deps = [
        ":control_slot_types",
        ":event_data_control_composite",
    ],
)

cc_library(
    name = "event",
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = [
        "//score/mw/com/impl/bindings/lola/messaging:__pkg__",
        "//score/mw/com/impl/bindings/lola/test:__pkg__",
        "//score/mw/com/impl/bindings/lola/test_doubles:__pkg__",
        "//score/mw/com/impl/plumbing:__pkg__",
    ],
    deps = [
        ":event_control",
        ":event_data_control",
        ":event_data_control_composite",
        ":event_data_storage",
        ":event_slot_status",
        ":event_subscription_control",
        ":sample_allocatee_ptr",
        ":sample_ptr",
    ],
)

cc_library(
    name = "transaction_log",
    srcs = ["transaction_log.cpp"],
    hdrs = ["transaction_log.h"],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = ["//score/mw/com/impl/bindings/lola:__subpackages__"],
    deps = [
        ":transaction_log_slot",
        "//score/memory/shared",
        "@score_baselibs//score/containers:dynamic_array",
    ],
)

cc_library(
    name = "transaction_log_local_view",
    srcs = ["transaction_log_local_view.cpp"],
    hdrs = ["transaction_log_local_view.h"],
    features = COMPILER_WARNING_FEATURES,
    implementation_deps = [
        "//score/mw/com/impl:error",
        "@score_baselibs//score/mw/log",
    ],
    tags = ["FFI"],
    visibility = ["//score/mw/com/impl/bindings/lola:__subpackages__"],
    deps = [
        ":control_slot_types",
        ":transaction_log",
        "//score/memory/shared",
        "@score_baselibs//score/containers:dynamic_array",
        "@score_baselibs//score/language/futurecpp",
    ],
)

cc_library(
    name = "transaction_log_id",
    srcs = ["transaction_log_id.cpp"],
    hdrs = ["transaction_log_id.h"],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = ["//score/mw/com/impl/bindings/lola:__subpackages__"],
)

# TransactionLogSet and TransactionLogRegistrationGuard are in the same build target to avoid cyclic dependency errors
cc_library(
    name = "transaction_log_index",
    srcs = ["transaction_log_index.cpp"],
    hdrs = ["transaction_log_index.h"],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = ["//score/mw/com/impl/bindings/lola:__subpackages__"],
    deps = [
        "//score/mw/com/impl/configuration",
    ],
)

cc_library(
    name = "transaction_log_set",
    srcs = [
        "transaction_log_registration_guard.cpp",
        "transaction_log_set.cpp",
    ],
    hdrs = [
        "transaction_log_registration_guard.h",
        "transaction_log_set.h",
    ],
    features = COMPILER_WARNING_FEATURES,
    implementation_deps = [
        "@score_baselibs//score/language/futurecpp",
        "@score_baselibs//score/mw/log",
    ],
    tags = ["FFI"],
    visibility = ["//score/mw/com/impl/bindings/lola:__subpackages__"],
    deps = [
        ":consumer_event_data_control_local_view",
        ":provider_event_data_control_local_view",
        ":transaction_log",
        ":transaction_log_id",
        ":transaction_log_index",
        ":transaction_log_local_view",
        "//score/mw/com/impl/configuration",
        "//score/mw/com/impl/util:copyable_atomic",
        "@score_baselibs//score/containers:dynamic_array",
        "@score_baselibs//score/result",
        "@score_baselibs//score/scope_exit",
    ],
)

cc_library(
    name = "transaction_log_rollback_executor",
    srcs = ["transaction_log_rollback_executor.cpp"],
    hdrs = ["transaction_log_rollback_executor.h"],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = ["//score/mw/com/impl/bindings/lola:__subpackages__"],
    deps = [
        ":service_data_control",
        ":transaction_log_id",
        ":transaction_log_set",
        "//score/mw/com/impl:runtime",
        "//score/mw/com/impl/bindings/lola:runtime",
        "@score_baselibs//score/language/futurecpp",
        "@score_baselibs//score/mw/log",
        "@score_baselibs//score/result",
    ],
)

cc_library(
    name = "transaction_log_slot",
    srcs = ["transaction_log_slot.cpp"],
    hdrs = ["transaction_log_slot.h"],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = ["//score/mw/com/impl/bindings/lola:__subpackages__"],
)

cc_library(
    name = "type_erased_sample_ptrs_guard",
    srcs = ["type_erased_sample_ptrs_guard.cpp"],
    hdrs = ["type_erased_sample_ptrs_guard.h"],
    features = COMPILER_WARNING_FEATURES,
    implementation_deps = [
        "//score/mw/com/impl/tracing:service_element_tracing_data",
    ],
    tags = ["FFI"],
    visibility = ["//score/mw/com/impl/bindings/lola:__subpackages__"],
    deps = [
        "//score/mw/com/impl:binding_type",
        "//score/mw/com/impl:runtime",
        "//score/mw/com/impl/tracing:i_binding_tracing_runtime",
    ],
)

cc_library(
    name = "proxy_instance_identifier",
    srcs = ["proxy_instance_identifier.cpp"],
    hdrs = ["proxy_instance_identifier.h"],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = [
        "//score/mw/com/impl/bindings/lola:__subpackages__",
    ],
    deps = [
        "//score/mw/com/impl/configuration",
        "@score_baselibs//score/mw/log",
    ],
)

cc_library(
    name = "skeleton_instance_identifier",
    srcs = ["skeleton_instance_identifier.cpp"],
    hdrs = ["skeleton_instance_identifier.h"],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = [
        "//score/mw/com/impl/bindings/lola:__subpackages__",
    ],
    deps = [
        "//score/mw/com/impl/configuration",
        "@score_baselibs//score/mw/log",
    ],
)

cc_unit_test(
    name = "partial_restart_path_builder_test",
    srcs = ["partial_restart_path_builder_test.cpp"],
    features = COMPILER_WARNING_FEATURES,
    visibility = [
        "//score/mw/com/impl:__subpackages__",
    ],
    deps = [":partial_restart_path_builder"],
)

cc_unit_test(
    name = "shm_path_builder_test",
    srcs = ["shm_path_builder_test.cpp"],
    features = COMPILER_WARNING_FEATURES,
    deps = [":shm_path_builder"],
)

cc_unit_test(
    name = "application_id_pid_mapping_test",
    srcs = ["application_id_pid_mapping_test.cpp"],
    features = COMPILER_WARNING_FEATURES,
    deps = [
        ":application_id_pid_mapping",
        "@score_baselibs//score/concurrency:atomic_indirector",
        "@score_baselibs//score/concurrency:atomic_indirector_mock_binding",
    ],
)

cc_unit_test(
    name = "generic_proxy_event_test",
    srcs = ["generic_proxy_event_test.cpp"],
    features = COMPILER_WARNING_FEATURES,
    deps = [
        ":proxy",
        "//score/mw/com/impl/bindings/lola/test:proxy_event_test_resources",
    ],
)

cc_unit_test(
    name = "generic_skeleton_event_test",
    srcs = ["generic_skeleton_event_test.cpp"],
    features = COMPILER_WARNING_FEATURES,
    deps = [
        ":generic_skeleton_event",
        "//score/mw/com/impl/bindings/lola/test:skeleton_event_test_resources",
    ],
)

cc_unit_test(
    name = "skeleton_method_test",
    srcs = ["skeleton_method_test.cpp"],
    features = COMPILER_WARNING_FEATURES + [
        # These tests catch exceptions instead of using gtest EXPECT_DEATH so we disable aborts_upon_exception.
        "-aborts_upon_exception",
    ],
    deps = [
        ":skeleton",
        "//score/mw/com/impl/bindings/lola/test:skeleton_test_resources",
        "//score/mw/com/impl/configuration/test:configuration_store",
        "@googletest//:gtest",
        "@score_baselibs//score/language/futurecpp:futurecpp_test_support",
    ],
)

cc_unit_test(
    name = "type_erased_sample_ptrs_guard_test",
    srcs = ["type_erased_sample_ptrs_guard_test.cpp"],
    features = COMPILER_WARNING_FEATURES,
    deps = [
        ":type_erased_sample_ptrs_guard",
        "//score/mw/com/impl:runtime",
        "//score/mw/com/impl:runtime_mock",
        "//score/mw/com/impl/bindings/mock_binding/tracing:tracing_runtime",
        "//score/mw/com/impl/test:runtime_mock_guard",
        "//score/mw/com/impl/tracing:tracing_runtime_mock",
    ],
)

cc_unit_test(
    name = "dynamic_array_bounds_checking_test",
    srcs = [
        "dynamic_array_bounds_checking_test.cpp",
    ],
    features = COMPILER_WARNING_FEATURES + [
        # These tests catch exceptions instead of using gtest EXPECT_DEATH so we disable aborts_upon_exception.
        "-aborts_upon_exception",
    ],
    visibility = [
        "//score/memory:__pkg__",
        "//score/mw/com/impl/bindings/lola:__subpackages__",
    ],
    deps = [
        "//score/memory/shared:polymorphic_offset_ptr_allocator",
        "//score/memory/shared/fake:fake_memory_resources",
        "@googletest//:gtest",
        "@score_baselibs//score/containers:dynamic_array",
        "@score_baselibs//score/containers:non_relocatable_vector",
        "@score_baselibs//score/language/futurecpp:futurecpp_test_support",
        "@score_baselibs//score/mw/log",
    ],
)

cc_unit_test(
    name = "event_data_control_test",
    srcs = ["event_data_control_test.cpp"],
    features = COMPILER_WARNING_FEATURES,
    deps = [
        ":event_data_control",
        ":event_slot_status",
        "@score_baselibs//score/containers:dynamic_array",
        "@score_baselibs//score/mw/log",
    ],
)

cc_unit_test(
    name = "provider_event_data_control_local_view_test",
    srcs = [
        "provider_event_data_control_local_view_test.cpp",
    ],
    features = COMPILER_WARNING_FEATURES + [
        "aborts_upon_exception",
    ],
    deps = [
        ":provider_event_data_control_local_view",
        "//score/mw/com/impl/bindings/lola:event_data_control",
        "//score/mw/com/impl/bindings/lola:event_slot_status",
        "//score/mw/com/impl/bindings/lola/test_doubles:fake_memory_resource",
        "@score_baselibs//score/concurrency:atomic_indirector_mock_binding",
        "@score_baselibs//score/mw/log",
    ],
)

cc_unit_test(
    name = "consumer_event_data_control_local_view_test",
    srcs = [
        "consumer_event_data_control_local_view_test.cpp",
    ],
    features = COMPILER_WARNING_FEATURES + [
        # These tests catch exceptions instead of using gtest EXPECT_DEATH so we disable aborts_upon_exception.
        "-aborts_upon_exception",
    ],
    deps = [
        ":consumer_event_data_control_local_view",
        ":provider_event_data_control_local_view",
        "//score/mw/com/impl/bindings/lola:event_data_control",
        "//score/mw/com/impl/bindings/lola/test_doubles:fake_memory_resource",
        "//score/mw/com/impl/configuration",
        "@score_baselibs//score/concurrency:atomic_indirector_mock_binding",
        "@score_baselibs//score/language/futurecpp:futurecpp_test_support",
        "@score_baselibs//score/mw/log",
    ],
)

cc_unit_test(
    name = "event_data_control_composite_test",
    srcs = ["event_data_control_composite_test.cpp"],
    features = COMPILER_WARNING_FEATURES,
    deps = [
        ":consumer_event_data_control_local_view",
        ":provider_event_data_control_local_view",
        "//score/memory/shared:new_delete_delegate_resource",
        "//score/mw/com/impl:instance_specifier",
        "//score/mw/com/impl/bindings/lola:event_data_control",
        "//score/mw/com/impl/bindings/lola:event_data_control_composite",
        "//score/mw/com/impl/bindings/lola/test_doubles:fake_memory_resource",
        "@score_baselibs//score/concurrency:atomic_indirector_mock_binding",
        "@score_baselibs//score/containers:dynamic_array",
        "@score_baselibs//score/language/futurecpp",
    ],
)

cc_unit_test(
    name = "skeleton_test",
    srcs = ["skeleton_test.cpp"],
    features = COMPILER_WARNING_FEATURES + [
        "aborts_upon_exception",
    ],
    deps = [
        ":skeleton",
        "//score/mw/com/impl/bindings/lola/test:skeleton_test_resources",
        "//score/mw/com/impl/bindings/lola/test:transaction_log_test_resources",
        "//score/mw/com/impl/bindings/mock_binding",
        "//score/mw/com/impl/tracing:tracing_runtime_mock",
    ],
)

cc_unit_test(
    name = "skeleton_method_handling_test",
    srcs = [
        "skeleton_method_handling_test.cpp",
    ],
    features = COMPILER_WARNING_FEATURES + [
        # These tests catch exceptions instead of using gtest EXPECT_DEATH so we disable aborts_upon_exception.
        "-aborts_upon_exception",
    ],
    deps = [
        ":skeleton",
        "//score/memory/shared:shared_memory_resource_mock",
        "//score/memory/shared/fake:my_bounded_shared_memory_resource",
        "//score/mw/com/impl:binding_type",
        "//score/mw/com/impl/bindings/lola/test:skeleton_test_resources",
        "//score/mw/com/impl/configuration/test:configuration_store",
        "@score_baselibs//score/language/futurecpp",
        "@score_baselibs//score/language/futurecpp:futurecpp_test_support",
        "@score_baselibs//score/memory:data_type_size_info",
        "@score_baselibs//score/result",
    ],
)

cc_unit_test(
    name = "skeleton_event_common_test",
    srcs = ["skeleton_event_common_test.cpp"],
    features = COMPILER_WARNING_FEATURES,
    deps = [
        ":skeleton",
        "//score/mw/com/impl/bindings/lola/test:skeleton_event_test_resources",
        "//score/mw/com/impl/bindings/lola/test:transaction_log_test_resources",
    ],
)

cc_unit_test(
    name = "proxy_test",
    srcs = ["proxy_test.cpp"],
    features = COMPILER_WARNING_FEATURES + [
        # SCORE_LANGUAGE_FUTURECPP_EXPECT_CONTRACT_VIOLATED catches an exception, so disable aborts_upon_exception.
        "-aborts_upon_exception",
    ],
    deps = [
        ":proxy",
        ":shm_path_builder_mock",
        "//score/mw/com/impl/bindings/lola/test:proxy_event_test_resources",
        "//score/mw/com/impl/bindings/lola/test:transaction_log_test_resources",
        "//score/mw/com/impl/bindings/mock_binding",
        "//score/mw/com/impl/configuration",
        "@score_baselibs//score/language/futurecpp:futurecpp_test_support",
        "@score_baselibs//score/result",
    ],
)

cc_unit_test(
    name = "proxy_method_handling_test",
    srcs = ["proxy_method_handling_test.cpp"],
    features = COMPILER_WARNING_FEATURES + [
        # These tests catch exceptions instead of using gtest EXPECT_DEATH so we disable aborts_upon_exception.
        "-aborts_upon_exception",
    ],
    deps = [
        ":proxy",
        "//score/memory/shared:shared_memory_resource_mock",
        "//score/memory/shared/fake:my_bounded_shared_memory_resource",
        "//score/mw/com/impl/bindings/lola/test:proxy_event_test_resources",
        "//score/mw/com/impl/configuration/test:configuration_store",
        "@googletest//:gtest",
        "@score_baselibs//score/filesystem:mock",
        "@score_baselibs//score/language/futurecpp:futurecpp_test_support",
    ],
)

cc_unit_test(
    name = "proxy_event_test",
    srcs = ["proxy_event_test.cpp"],
    features = COMPILER_WARNING_FEATURES,
    deps = [
        ":proxy",
        "//score/mw/com/impl/bindings/lola/test:proxy_event_test_resources",
    ],
)

cc_unit_test(
    name = "proxy_event_e2e_test",
    srcs = ["proxy_event_e2e_test.cpp"],
    features = COMPILER_WARNING_FEATURES,
    deps = [
        ":proxy",
        "//score/mw/com/impl/configuration",
        "//score/mw/com/impl/e2e:e2e_profile_stub",
        "//score/mw/com/impl/bindings/lola/test:proxy_event_test_resources",
    ],
)

cc_unit_test(
    name = "slot_decrementer_test",
    srcs = ["slot_decrementer_test.cpp"],
    features = COMPILER_WARNING_FEATURES,
    deps = [
        ":consumer_event_data_control_local_view",
        ":event_data_control",
        ":provider_event_data_control_local_view",
        ":slot_decrementer",
        "//score/mw/com/impl/bindings/lola/test_doubles:fake_memory_resource",
    ],
)

cc_unit_test(
    name = "transaction_log_rollback_executor_test",
    srcs = ["transaction_log_rollback_executor_test.cpp"],
    features = COMPILER_WARNING_FEATURES,
    deps = [
        ":rollback_synchronization",
        ":runtime_mock",
        ":skeleton",
        ":transaction_log_rollback_executor",
        "//score/memory/shared:shared_memory_resource_heap_allocator_mock",
        "//score/mw/com/impl:runtime",
        "//score/mw/com/impl:runtime_mock",
        "//score/mw/com/impl/bindings/lola/messaging:message_passing_service_mock",
        "//score/mw/com/impl/bindings/lola/test:transaction_log_test_resources",
        "//score/mw/com/impl/test:runtime_mock_guard",
    ],
)

cc_unit_test(
    name = "element_fq_id_test",
    srcs = [
        "element_fq_id_test.cpp",
    ],
    features = COMPILER_WARNING_FEATURES,
    deps = [
        ":element_fq_id",
        "@score_baselibs//score/mw/log",
    ],
)

cc_unit_test(
    name = "event_data_storage_test",
    srcs = [
        "event_data_storage_test.cpp",
    ],
    features = COMPILER_WARNING_FEATURES,
    deps = [
        ":event_data_storage",
        "@score_baselibs//score/containers:dynamic_array",
        "@score_baselibs//score/mw/log",
    ],
)

cc_unit_test(
    name = "event_slot_status_test",
    srcs = [
        "event_slot_status_test.cpp",
    ],
    features = COMPILER_WARNING_FEATURES,
    deps = [
        ":event_slot_status",
    ],
)

cc_unit_test(
    name = "event_subscription_control_test",
    srcs = [
        "event_subscription_control_test.cpp",
    ],
    features = COMPILER_WARNING_FEATURES,
    deps = [
        ":event_subscription_control",
        "//score/mw/com/impl/bindings/lola/test:proxy_event_test_resources",
        "@score_baselibs//score/concurrency:atomic_indirector_mock_binding",
    ],
)

cc_unit_test(
    name = "proxy_event_common_test",
    srcs = [
        "proxy_event_common_test.cpp",
    ],
    features = COMPILER_WARNING_FEATURES,
    deps = [
        ":proxy",
        "//score/mw/com/impl/bindings/lola/test:proxy_event_test_resources",
    ],
)

cc_unit_test(
    name = "runtime_test",
    srcs = [
        "runtime_test.cpp",
    ],
    features = COMPILER_WARNING_FEATURES,
    deps = [
        ":runtime",
        # TODO: Change for mock once it provides all symbols (see https://github.com/eclipse-score/baselibs/issues/198)
        "@score_baselibs//score/analysis/tracing/generic_trace_library:implementation",
        "@score_baselibs//score/os/mocklib:unistd_mock",
    ],
)

cc_unit_test(
    name = "sample_allocatee_ptr_test",
    srcs = [
        "sample_allocatee_ptr_test.cpp",
    ],
    features = COMPILER_WARNING_FEATURES,
    deps = [
        "//score/mw/com/impl/bindings/lola/test_doubles",
    ],
)

cc_unit_test(
    name = "sample_ptr_test",
    srcs = [
        "sample_ptr_test.cpp",
    ],
    features = COMPILER_WARNING_FEATURES,
    deps = [
        "//score/mw/com/impl/bindings/lola/test_doubles",
    ],
)

cc_unit_test(
    name = "service_data_storage_test",
    srcs = [
        "service_data_storage_test.cpp",
    ],
    features = COMPILER_WARNING_FEATURES,
    deps = [
        ":element_fq_id",
        ":event_meta_info",
        ":runtime_mock",
        ":service_data_storage",
        "//score/memory/shared:new_delete_delegate_resource",
        "//score/mw/com/impl:binding_type",
        "//score/mw/com/impl/test:runtime_mock_guard",
        "@score_baselibs//score/memory:data_type_size_info",
        "@score_baselibs//score/os:object_seam",
        "@score_baselibs//score/os/mocklib:unistd_mock",
    ],
)

cc_unit_test(
    name = "service_data_control_test",
    srcs = [
        "service_data_control_test.cpp",
    ],
    features = COMPILER_WARNING_FEATURES,
    deps = [
        ":element_fq_id",
        ":event_control",
        ":service_data_control",
        "//score/memory/shared:new_delete_delegate_resource",
        "//score/mw/com/impl:service_element_type",
    ],
)

cc_unit_test(
    name = "linear_search_map_test",
    srcs = [
        "linear_search_map_test.cpp",
    ],
    features = COMPILER_WARNING_FEATURES,
    deps = [
        ":linear_search_map",
        "//score/memory/shared:new_delete_delegate_resource",
        "@score_baselibs//score/mw/log",
    ],
)

cc_unit_test(
    name = "skeleton_event_test",
    srcs = [
        "skeleton_event_test.cpp",
    ],
    features = COMPILER_WARNING_FEATURES + [
        # These tests catch exceptions instead of using gtest EXPECT_DEATH so we disable aborts_upon_exception.
        "-aborts_upon_exception",
    ],
    deps = [
        "//score/mw/com/impl/bindings/lola/test:skeleton_event_test_resources",
        "@score_baselibs//score/language/futurecpp:futurecpp_test_support",
    ],
)

cc_unit_test(
    name = "skeleton_event_e2e_test",
    srcs = [
        "skeleton_event_e2e_test.cpp",
    ],
    features = COMPILER_WARNING_FEATURES,
    deps = [
        "//score/mw/com/impl/bindings/lola/test:skeleton_event_test_resources",
        "//score/mw/com/impl/configuration",
        "//score/mw/com/impl/e2e:e2e_profile_stub",
    ],
)

cc_unit_test(
    name = "skeleton_event_tracing_test",
    srcs = [
        "skeleton_event_tracing_test.cpp",
    ],
    features = COMPILER_WARNING_FEATURES,
    deps = [
        "//score/mw/com/impl/bindings/lola/test:skeleton_event_test_resources",
        "//score/mw/com/impl/bindings/lola/test:transaction_log_test_resources",
        "//score/mw/com/impl/tracing/configuration:tracing_filter_config_mock",
    ],
)

cc_unit_test(
    name = "slot_collector_test",
    srcs = [
        "slot_collector_test.cpp",
    ],
    features = COMPILER_WARNING_FEATURES,
    deps = [
        ":consumer_event_data_control_local_view",
        ":provider_event_data_control_local_view",
        ":slot_collector",
        "//score/mw/com/impl/bindings/lola/test_doubles",
    ],
)

cc_unit_test(
    name = "subscription_helpers_test",
    srcs = [
        "subscription_helpers_test.cpp",
    ],
    features = COMPILER_WARNING_FEATURES,
    deps = [
        ":subscription_state_machine",
    ],
)

cc_unit_test(
    name = "subscription_state_machine_events_test",
    srcs = [
        "subscription_state_machine_events_test.cpp",
    ],
    features = COMPILER_WARNING_FEATURES,
    deps = [
        ":subscription_state_machine",
        "//score/mw/com/impl/bindings/lola/test:proxy_event_test_resources",
        "//score/mw/com/impl/bindings/lola/test:transaction_log_test_resources",
    ],
)

cc_unit_test(
    name = "subscription_state_machine_methods_test",
    srcs = [
        "subscription_state_machine_methods_test.cpp",
    ],
    features = COMPILER_WARNING_FEATURES,
    deps = [
        ":subscription_state_machine",
        "//score/mw/com/impl/bindings/lola/test:proxy_event_test_resources",
    ],
)

cc_unit_test(
    name = "subscription_state_machine_stress_test",
    srcs = [
        "subscription_state_machine_stress_test.cpp",
    ],
    features = COMPILER_WARNING_FEATURES,
    deps = [
        ":subscription_state_machine",
        "//score/mw/com/impl/bindings/lola/test:proxy_event_test_resources",
    ],
)

cc_unit_test(
    name = "subscription_state_machine_states_test",
    srcs = [
        "subscription_state_machine_states_test.cpp",
    ],
    features = COMPILER_WARNING_FEATURES,
    deps = [
        ":subscription_state_machine",
    ],
)

cc_unit_test(
    name = "transaction_log_registration_guard_test",
    srcs = [
        "transaction_log_registration_guard_test.cpp",
    ],
    features = COMPILER_WARNING_FEATURES,
    deps = [
        ":transaction_log_set",
        "//score/mw/com/impl/bindings/lola/test:transaction_log_test_resources",
    ],
)

cc_unit_test(
    name = "transaction_log_set_test",
    srcs = [
        "transaction_log_set_test.cpp",
    ],
    features = COMPILER_WARNING_FEATURES + [
        # These tests catch exceptions instead of using gtest EXPECT_DEATH so we disable aborts_upon_exception.
        "-aborts_upon_exception",
    ],
    deps = [
        "//score/mw/com/impl/bindings/lola:runtime_mock",
        "//score/mw/com/impl/bindings/lola/test:transaction_log_test_resources",
        "//score/mw/com/impl/test:runtime_mock_guard",
        "@score_baselibs//score/language/futurecpp:futurecpp_test_support",
    ],
)

cc_unit_test(
    name = "transaction_log_slot_test",
    srcs = [
        "transaction_log_slot_test.cpp",
    ],
    features = COMPILER_WARNING_FEATURES,
    deps = [
        ":transaction_log_slot",
    ],
)

cc_unit_test(
    name = "transaction_log_local_view_test",
    srcs = [
        "transaction_log_local_view_test.cpp",
    ],
    features = COMPILER_WARNING_FEATURES,
    deps = [
        ":transaction_log",
        "//score/memory/shared:shared_memory_resource_heap_allocator_mock",
        "//score/mw/com/impl/bindings/lola/test:transaction_log_test_resources",
    ],
)

cc_unit_test(
    name = "runtime_application_id_test",
    srcs = [
        "runtime_application_id_test.cpp",
    ],
    features = COMPILER_WARNING_FEATURES,
    deps = [
        ":runtime",
        # TODO: Change for mock once it provides all symbols (see https://github.com/eclipse-score/baselibs/issues/198)
        "@score_baselibs//score/analysis/tracing/generic_trace_library:implementation",
        "@score_baselibs//score/os/mocklib:unistd_mock",
    ],
)

cc_unit_test(
    name = "proxy_instance_identifier_test",
    srcs = ["proxy_instance_identifier_test.cpp"],
    deps = [
        ":proxy_instance_identifier",
        "@score_baselibs//score/mw/log",
        "@score_baselibs//score/mw/log:recorder_mock",
    ],
)

cc_unit_test(
    name = "skeleton_instance_identifier_test",
    srcs = ["skeleton_instance_identifier_test.cpp"],
    deps = [
        ":skeleton_instance_identifier",
        "@score_baselibs//score/mw/log:recorder_mock",
    ],
)

cc_unit_test(
    name = "proxy_method_test",
    srcs = [
        "proxy_method_test.cpp",
    ],
    features = COMPILER_WARNING_FEATURES + [
        # These tests catch exceptions instead of using gtest EXPECT_DEATH so we disable aborts_upon_exception.
        "-aborts_upon_exception",
    ],
    deps = [
        "i_runtime",
        ":element_fq_id",
        ":proxy",
        "//score/mw/com/impl",
        "//score/mw/com/impl/bindings/lola/test:proxy_event_test_resources",
        "//score/mw/com/impl/configuration/test:configuration_store",
        "@googletest//:gtest",
        "@score_baselibs//score/language/futurecpp:futurecpp_test_support",
        "@score_baselibs//score/memory:data_type_size_info",
        "@score_baselibs//score/mw/log",
        "@score_baselibs//score/result",
    ],
)
